gantt
    title gantt de gestion de projet

    section Conception
    faire une étude des profils de l équipe (tout le monde): 2023-12-11, 1d
    construire une maquette physique (YG)       : 2023-12-16, 30d
    conception du logiciel  (Diallo, karim)     : 2023-12-16, 10d
    faire une maquette du logiciel de contrôle (Diallo, karim)  : 2023-12-26, 35d
    rechercher la législation sur les drônes pour prévoir les démarches à suivre (chaymae, mohamed): 2023-12-25, 7d
    faire une étude de marché définir les clients et les compétiteurs (asmae,chaymae): 2023-12-18, 7d
    établir un budget (chaymae, asmae, mohammed)                           : 2024-01-01, 3d
    rechercher les aides financières auxquelles l'entreprise aurait droit (): 2024-01-03, 4d
    préparer l oral (tout le monde)                            : 2023-12-25, 21d
    remplir le carnet de bord (périodique)      : 2023-12-11, 60d
    concevoir le système de contrôle (Samir)            : 2023-12-11, 40d
    préparer un powerpoint pour l oral  (tout le monde)        : 2024-01-01, 14d
    choisir une architecture IA (YG, samir)                : 2024-01-01, 7d
