gantt
    title Projet Wingman - Développement de l'Aile Volante Autonome

    section Conception
    Conception de l'aile volante (YG)              : 2023-01-01, 7d
    Conception du système de propulsion (YG)       : 2023-01-08, 7d
    Conception du système de vol (Amineel Moursli) : 2023-01-15, 7d
    Conception du système de détection (Asmae Morabet) : 2023-01-15, 7d
    Conception du système de contrôle (YG)         : 2023-01-22, 7d
    Conception du système informatique (YG/Diallo)        : 2023-01-29, 40d
    Conception du système sonore et lumineux (Diallo)  : 2023-01-08, 20d
    Conception de l'application multi-plateforme de contrôle (YG/Diallo) : 2023-03-10, 60d

    section Fabrication
    Fabrication de l'aile volante (BI)             : 2023-01-15, 14d
    Assemblage du système de propulsion (BI)       : 2023-01-22, 14d
    Assemblage du système de vol (BI)              : 2023-02-05, 14d
    Assemblage du système de détection (BI)        : 2023-02-19, 14d
    Assemblage du système de contrôle (BI)         : 2023-03-05, 14d
    Assemblage du système informatique (BI)        : 2023-03-19, 14d
    Assemblage du système sonore et lumineux (BI)  : 2023-04-02, 14d

    section Tests
    Tests du système de propulsion (Ahmed Karim)    : 2023-03-05, 14d
    Tests du système de vol (Samir)                 : 2023-02-19, 14d
    Tests du système de détection (Samir)           : 2023-03-05, 14d
    Tests du système de contrôle (Samir)            : 2023-03-19, 14d
    Tests du système informatique (Samir)           : 2023-04-02, 14d
    Tests du système complet (Samir)               : 2023-04-16, 14d

    section Déploiement
    Intégration du système sur l'aile volante (Asmae Morabet) : 2023-04-30, 7d
    Tests sur le terrain (Oumarl Abe)                        : 2023-05-07, 14d
    Optimisation et ajustements (Oumarl Abe)                  : 2023-05-21, 14d

    section Documentation
    Rédaction de la documentation technique (Oumarl Abe)   : 2023-06-04, 7d
    Création du manuel d'utilisation (Oumarl Abe)          : 2023-06-11, 7d
    Préparation des rapports de conception (Amineel Moursli)             : 2023-02-19, 7d
    Rapport préliminaire de conception (Amineel Moursli)                : 2023-02-26, 7d
    Rapport préliminaire de fabrication (BI)               : 2023-04-16, 7d
    Rapport préliminaire des tests (Ahmed Karim)           : 2023-04-30, 7d
    Rapport préliminaire de déploiement (Oumarl Abe)       : 2023-05-21, 7d
    Élaboration du rapport final de projet (Oumarl Abe)      : 2023-06-18, 14d
